username: "postgres"
password: "admin"
url: "jdbc:postgresql://localhost:5432/postgres"

spring:
  datasource:
    username: "postgres"
    password: "admin"
    url: "jdbc:postgresql://localhost:5432/postgres"
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true